


spring:
 datasource:
  type: org.apache.commons.dbcp2.BasicDataSource
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:orcl
  password: tiger
  username: scott